# Generated by Django 6.0.5 on 2026-05-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Правовой Пилигрим', max_length=150, verbose_name='Название сайта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('working_hours', models.TextField(blank=True, verbose_name='Режим работы')),
                ('company_details', models.TextField(blank=True, verbose_name='Реквизиты компании')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('yandex_metrika_id', models.CharField(blank=True, max_length=50, verbose_name='ID Яндекс Метрики')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='ID Google Analytics')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
