# Generated by Django 6.0.5 on 2026-05-22 05:24

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=70, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='OG Image')),
                ('is_indexable', models.BooleanField(default=True, verbose_name='Индексировать (index)')),
                ('is_followable', models.BooleanField(default=True, verbose_name='Переходить по ссылкам (follow)')),
                ('schema_type', models.CharField(blank=True, help_text='Например: WebPage, Article, Service, FAQPage, LegalService', max_length=50, verbose_name='Schema.org Type')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, max_digits=2, verbose_name='Sitemap Priority')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('h1', models.CharField(blank=True, max_length=200, verbose_name='H1')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Контент')),
                ('tags', models.CharField(blank=True, help_text='Теги через запятую', max_length=255, verbose_name='Теги')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Обложка')),
                ('is_news', models.BooleanField(default=False, verbose_name='Новость')),
                ('is_expert_article', models.BooleanField(default=False, verbose_name='Экспертная статья')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Время чтения в минутах', verbose_name='Время чтения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
