# Generated by Django 6.0.5 on 2026-05-22 05:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=70, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='OG Image')),
                ('is_indexable', models.BooleanField(default=True, verbose_name='Индексировать (index)')),
                ('is_followable', models.BooleanField(default=True, verbose_name='Переходить по ссылкам (follow)')),
                ('schema_type', models.CharField(blank=True, help_text='Например: WebPage, Article, Service, FAQPage, LegalService', max_length=50, verbose_name='Schema.org Type')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, max_digits=2, verbose_name='Sitemap Priority')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('h1', models.CharField(blank=True, max_length=200, verbose_name='H1')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Контент')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Иконка')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/covers/', verbose_name='Обложка')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая услуга')),
                ('faq_items', models.ManyToManyField(blank=True, related_name='services', to='faq.faq', verbose_name='FAQ')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='services', to='blog.blogpost', verbose_name='Связанные статьи')),
                ('related_services', models.ManyToManyField(blank=True, to='services.service', verbose_name='Связанные услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
