# Generated by Django 6.0.5 on 2026-05-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('debt_amount', models.CharField(blank=True, max_length=100, verbose_name='Сумма долга')),
                ('source_page', models.URLField(blank=True, verbose_name='Страница отправки')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(blank=True, max_length=200, verbose_name='UTM Content')),
                ('utm_term', models.CharField(blank=True, max_length=200, verbose_name='UTM Term')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('consent_accepted', models.BooleanField(default=True, verbose_name='Согласие на обработку ПД')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('done', 'Завершен'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('lead_type', models.CharField(choices=[('default', 'По умолчанию'), ('quiz', 'Квиз'), ('callback', 'Обратный звонок')], default='default', max_length=20, verbose_name='Тип заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
