# Generated by Django 6.0.5 on 2026-05-22 05:24

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ответ')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_entries', to='blog.blogpost', verbose_name='Связанная статья')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
