# Generated by Django 6.0.5 on 2026-09-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('indexing_enabled', models.BooleanField(default=True, help_text='Тестовый домен дополнительно закрыт настройками окружения.', verbose_name='Разрешить индексацию основного сайта')),
                ('site_name', models.CharField(default='Правовой Пилигрим', max_length=100, verbose_name='Название сайта')),
                ('default_description', models.CharField(default='Банкротство физических лиц и списание долгов в Астрахани и Астраханской области. Юридическая консультация и сопровождение процедуры.', max_length=300, verbose_name='Описание по умолчанию')),
                ('default_og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='Изображение для соцсетей')),
                ('google_verification', models.CharField(blank=True, help_text='Только значение content из метатега, без HTML.', max_length=255, verbose_name='Код подтверждения Google Search Console')),
                ('yandex_verification', models.CharField(blank=True, max_length=255, verbose_name='Код подтверждения Яндекс Вебмастера')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='Название организации')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Полный адрес офиса')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон организации')),
                ('area_served', models.CharField(default='Астрахань и Астраханская область', max_length=200, verbose_name='Регион обслуживания')),
            ],
            options={
                'verbose_name': 'Общие настройки SEO',
                'verbose_name_plural': 'Общие настройки SEO',
            },
        ),
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=70, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='OG Image')),
                ('is_indexable', models.BooleanField(default=True, verbose_name='Индексировать (index)')),
                ('is_followable', models.BooleanField(default=True, verbose_name='Переходить по ссылкам (follow)')),
                ('schema_type', models.CharField(blank=True, help_text='Например: WebPage, Article, Service, FAQPage, LegalService', max_length=50, verbose_name='Schema.org Type')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, max_digits=2, verbose_name='Sitemap Priority')),
                ('path', models.CharField(choices=[('/', 'Главная'), ('/bankrotstvo-fizicheskih-lic', 'Банкротство физических лиц'), ('/spisanie-dolgov', 'Списание долгов'), ('/bankrotstvo-pod-klyuch', 'Банкротство под ключ'), ('/bankrotstvo-cherez-mfc', 'Банкротство через МФЦ'), ('/kollektory', 'Защита от коллекторов'), ('/services', 'Юридические услуги'), ('/blog', 'Новости и статьи'), ('/cases', 'Кейсы'), ('/reviews', 'Отзывы'), ('/faq', 'Частые вопросы'), ('/contacts', 'Контакты'), ('/privacy-policy', 'Политика конфиденциальности'), ('/personal-data-consent', 'Согласие на обработку данных')], max_length=255, unique=True, verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'SEO статической страницы',
                'verbose_name_plural': 'SEO статических страниц',
            },
        ),
    ]
