# Generated by Django 6.0.5 on 2026-09-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoconfiguration',
            name='indexnow_enabled',
            field=models.BooleanField(default=False, help_text='Требуется INDEXNOW_KEY в окружении. Отправка только с SITE_URL=https://piligrim30.ru.', verbose_name='Уведомлять Яндекс через IndexNow'),
        ),
    ]
