# Generated by Django 6.0.5 on 2026-05-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('old_path', models.CharField(db_index=True, max_length=255, verbose_name='Старый путь')),
                ('new_path', models.CharField(max_length=255, verbose_name='Новый путь')),
                ('status_code', models.IntegerField(choices=[(301, '301 - Перемещено навсегда'), (302, '302 - Временно перемещено')], default=301, verbose_name='Код ответа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Редирект',
                'verbose_name_plural': 'Редиректы',
                'unique_together': {('old_path', 'is_active')},
            },
        ),
    ]
